sdk: "/Users/MOHUS/rhodes"
sdkversion: 3.2.1
name: BundleReplace
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.1
  provisionprofile: 0C0F1664-BE89-430A-9FDE-231538F657B2
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.customerapp
  BundleURLScheme: bundlereplace1
wp:
  productid: '2228d4b0-f751-012e-75a5-60f84732cfd8'
symbian:
  uid: '0xe8dbfaac'
android:
  version: 4.0.3

extensions: ["json"]
